### PR TITLE
ArgoCD official operator instructions

### PR DESCRIPTION
**Pull request by mihainueleanuibm**
Installation instructions for ArgoCD on OpenShift 4.3 via Operator Hub. 

Needs further work for Kubernetes. And we need to ensure minikube & CRD testing.

### CODE REVIEW

**Comment by bkribbs15** [comment]
Hey @mihainueleanuibm took a look at the PR and it looks like the openshift instructions were added to the IKS section of the lab so we would need to move the instructions over to the Openshift section.  The page is using tabs, so it can get a bit confusing.  No big deal though.

The other thing was using the UI vs a CLI for installation.  What do you think of having both in there with a tab similar to the whole lab that way the student can pick which they prefer? Our thought has always been sticking to the CLI has always been a better teaching approach since it is constant and sometimes there may not be a UI to access. That's something we can discuss though, open to either way just want talk about it before merging.

**Comment by csantanapr** [comment]
+1 On not using UI for the lab, let's use cli with yaml to install/setup operator

**Comment by mihainueleanuibm** [comment]
> Hey @mihainueleanuibm took a look at the PR and it looks like the openshift instructions were added to the IKS section of the lab so we would need to move the instructions over to the Openshift section. The page is using tabs, so it can get a bit confusing. No big deal though.

Apologies for that. 

> The other thing was using the UI vs a CLI for installation. What do you think of having both in there with a tab similar to the whole lab that way the student can pick which they prefer? Our thought has always been sticking to the CLI has always been a better teaching approach since it is constant and sometimes there may not be a UI to access. That's something we can discuss though, open to either way just want talk about it before merging.

👍 sounds good to me

**Comment by csantanapr** [comment]
I’m +1 on switching argocd operators if it’s kept more up to date and more OpenShift friendly.

**Comment by csantanapr** [comment]
superseded by #86

**Pull request closed without merging**
